### ISSUE TITLE
Bug: Inconsistent thumbnail sizes

### ISSUE THREAD

**Issue by RobTheFiveNine** [RobTheFiveNine/node-video-player#1]
## Problem
If thumbnail images are of differing sizes, they will display inconsistently. For example if all thumbnails are 100px in height, and a single thumbnail is 200px in height, then it will take up more vertical space then the rest of the thumbnails.

An example of this bug can be found below: ![thumbnail-bug](https://user-images.githubusercontent.com/49003204/95250868-a116ed80-0812-11eb-819a-db3ccfd6daf8.png)

## Proposed Solution
Change all thumbnails to be a fixed size and use the [object-fit: cover](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) CSS attribute to make the image fit without stretching it

**Comment by Rayleigh3105** [comment]
Can I take on this Bug?

**Comment by RobTheFiveNine** [comment]
> Can I take on this Bug?

Sure!

**Comment by Row** [comment]
Doing the hacktober. I created a PR for this #5, since this has been idle the last 15 days. Hope that is ok, otherwise you can use it for inspiration.

**Comment by RobTheFiveNine** [comment]
Thanks @Row - works great! I've tagged the PR with the Hacktoberfest label too 😃
